Task/bam 161 release from an input tag in anywhere (#8)
* BAM-161: Release from input tag

* BAM-161: Use the right version of spec to generate sdk

* BAM-161: Improve error handling

* BAM-161: Try powershell

* BAM-161: allow to publish prerelease version

* BAM-161: add some properties

* BAM-161: include ordering spec

* BAM-161: message for powershell

* BAM-161: pass the env variable

* BAM-161: remove unhelpful properties

diff --git a/.github/workflows/dotnet8-deploy.yml b/.github/workflows/dotnet8-deploy.yml
--- a/.github/workflows/dotnet8-deploy.yml
+++ b/.github/workflows/dotnet8-deploy.yml
@@ -1,6 +1,11 @@
 name: .NET8 Build and Release
 on:
   workflow_dispatch:
+    inputs:
+      kp_tag:
+        description: 'Optional tag for kp-protocols-clientsdk'
+        required: false
+        default: ''
 
 jobs:
   tagging:
@@ -10,21 +15,27 @@ jobs:
       version: ${{ steps.tag.outputs.version }}
       prerelease: ${{ steps.tag.outputs.prerelease }}
     steps:
-      - name: Fetch head tag from kp-protocols-clientsdk
+      - name: Fetch version tag from kp-protocols-clientsdk
         id: tag
         run: |
-          git clone --branch main https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
-          cd proto-repo
-          head_tag=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
-          if [[ -z "${head_tag}" ]]; then
+          if [ -n "${{ github.event.inputs.kp_tag }}" ]; then
+            git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
+            cd proto-repo || { echo "Failed to change directory to proto-repo"; exit 1; }
+            git checkout tags/${{ github.event.inputs.kp_tag }} -b temp-branch || { echo "Failed to checkout tag ${{ github.event.inputs.kp_tag }}"; exit 1; }
+            version_tag=${{ github.event.inputs.kp_tag }}
+          else
+            git clone --branch main https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
+            cd proto-repo
+            version_tag=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
+          fi
+          if [[ -z "${version_tag}" ]]; then
             echo "No tag found on the head commit of kp-protocols-clientsdk repo. Failing the action."
             exit 1
           else
-            echo "tag=${head_tag}" >> $GITHUB_OUTPUT
-            echo "version=${head_tag#v}" >> $GITHUB_OUTPUT
-            if [[ "${head_tag}" == *-* ]]; then echo "prerelease=true" >> $GITHUB_OUTPUT; else echo "prerelease=false" >> $GITHUB_OUTPUT; fi
+            echo "tag=${version_tag}" >> $GITHUB_OUTPUT
+            echo "version=${version_tag#v}" >> $GITHUB_OUTPUT
+            if [[ "${version_tag}" == *-* ]]; then echo "prerelease=true" >> $GITHUB_OUTPUT; else echo "prerelease=false" >> $GITHUB_OUTPUT; fi
           fi
-
   tagging-echo:
     needs:
       - tagging
@@ -47,6 +58,19 @@ jobs:
       - name: Checkout proto repository
         run: |
           git clone https://github.com/KodyPay/kp-protocols-clientsdk.git proto-repo
+          cd proto-repo
+          if ($env:GITHUB_EVENT_INPUTS_KP_TAG) {
+            git checkout tags/$env:GITHUB_EVENT_INPUTS_KP_TAG -b temp-branch
+            if ($LASTEXITCODE -ne 0) {
+              Write-Error "Failed to checkout tag $env:GITHUB_EVENT_INPUTS_KP_TAG"
+              exit 1
+            }
+          } else {
+            Write-Output "Environment variable GITHUB_EVENT_INPUTS_KP_TAG does not have a value."
+          }
+          cd ..
+        env:
+          GITHUB_EVENT_INPUTS_KP_TAG: ${{ github.event.inputs.kp_tag }}
 
       - name: Setup dotnet
         uses: actions/setup-dotnet@v3
@@ -62,7 +86,6 @@ jobs:
         run: dotnet pack --configuration Release -p:PackageVersion=${{ needs.tagging.outputs.version }} dotnet8
 
       - name: Publish to NuGet
-        if: ${{ needs.tagging.outputs.prerelease == 'false' }}
         run: dotnet nuget push --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json dotnet8\bin\Release\kody-dotnet8-client.*.nupkg
         # TODO: Sign package
 
